language: ruby
cache: bundler
rvm:
- 2.3.1
script: bundle exec rake
services:
  - redis
gemfile:
  - Gemfile
notifications:
  email:
    recipients:
    - vijay.krishna.ramesh@gmail.com
    on_failure: change
    on_success: never
env:
  global:
    secure: MK+CWQzMGTGzDRGfwtkJoAySnjcmmbEF4Fl9DDRaUD0q/LGTEV3TrOo+/QAeT945Vbs+CRnSMdGmVdBsLLiGlU56SrLQs8cEI/m7KyDcMjHJfuSkV5hdoUxSGgvvDlhLAZHBhmBnDnuIB7s0ExCyyJGamPOoZbVNgLYpF0XnxsY=
